### ISSUE TITLE
vtk python wheel doesn't include the vtkpthon executable which will be created in the non-wheel building way.

### ISSUE THREAD

**Issue by hongyi-zhao** [jcfr/VTKPythonPackage#47]
Hi,

I posted this problem [here](https://discourse.vtk.org/t/use-dvtk-wheel-build-on-dvtk-wrap-python-on-will-disable-the-creation-for-vtkpython/3528) but not been answered till now and I take the liberty post it here again. I noticed there are some differences between the wheel and the non-wheel building method for vtk. Say, the vtkpython tool will be created in the latter while it won't exist in wheel file. 

Any hints for this problem?

Regards,
HY

**Comment by prabhuramachandran** [comment]
The vtkpython executable is of no use when you have a working wheel -- at least I have never used it.  What is it that you need with the vtkpython executable?

**Comment by hongyi-zhao** [comment]
Thanks for your explanation. I really just want to know why it's created for the non-wheel distribution case.

**Comment by prabhuramachandran** [comment]
Please be more specific.  The vtkpython executable is just a convenience so that the VTK libraries are easier to load.  It  is not the same as your environment's Python.  Think of it as a separate Python binary that is able to load VTK.  So if you are only using VTK that is OK but for most people who are using Python for a dozen other things (and packages), this does not work.  When you have a wheel, you do not need vtkpython because the wheel is built so that the Python environment in which install the wheel into is able to load VTK and so you are able to use your own Python packages, other packages, and VTK as well.  Further, you can use this wheel in whatever environment you want.  So vtkpython is completely unnecessary when you build a wheel.

**Comment by hongyi-zhao** [comment]
Thanks a lot for your insightful analysis.
